### ISSUE TITLE
mcmmo world permissions not working when /ptp acceptall enabled.

### ISSUE THREAD

**Issue by andrewkm** [mcMMO-Dev/mcMMO-Classic#54]
Config as such:
```
    ptp:
        Cooldown: 10
        Warmup: 5
        RecentlyHurt_Cooldown: 30
        Accept_Required: true
        Request_Timeout: 60
        # If true, require players to have a mcmmo.commands.ptp.world.[WorldName] permission
        # to teleport to, from, or within any given world.
        World_Based_Permissions: true
```

bob does not have mcmmo.commands.ptp.world.nether

If bob does **/ptp jim** and jim is in world nether, bob cannot teleport to them. **CORRECT!**

If bob does **/ptp jim** and jim has **/ptp acceptall** enabled, and is in world nether, bob CAN teleport to them. **INCORRECT!**

Please fix <3
